- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    ECS_NAME: "${ECS_NAME}"
    STATE_RES_NAME: "${STATE_RES_NAME}"
  tasks:
    - name: Create ECS Cluster {{ ECS_NAME }}
      ecs_cluster:
        name: "{{ ECS_NAME }}"
      register: ecs

    - debug:
        var: ecs

#    - name: run cmd
#      shell: |
#        shipctl post_resource_state "{{ STATE_RES_NAME }}" versionName "build-${BUILD_NUMBER}"
#        shipctl put_resource_state "{{ STATE_RES_NAME }}" VPC_ID "{{ vpc.vpc.id }}"
#        shipctl put_resource_state "{{ STATE_RES_NAME }}" ECS_NAME "{{ ECS_NAME }}"
