- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    ECS_CLUSTER_NAME: "${ECS_CLUSTER_NAME}"
    INST_COUNT: "${INST_COUNT}"
    INST_TAG: "${INST_TAG}"
    INST_TYPE: "${INST_TYPE}"
    VPC_SUBNET_ID: "${VPC_SUBNET_ID}"
    INST_PROF_NAME: "${INST_PROF_NAME}"
    STATE_RES_NAME: "${STATE_RES_NAME}"
  tasks:
    - name: run cmd
      shell: |
        shipctl post_resource_state "{{ STATE_RES_NAME }}" versionName "build-${BUILD_NUMBER}"

    - name: Terminate {{ INST_COUNT }} instances with tag {{ INST_TAG }}
      ec2:
         key_name: demo-key
         group: default
         vpc_subnet_id: "{{ VPC_SUBNET_ID }}"
         instance_type: "{{ INST_TYPE }}"
         image: ami-9eb4b1e5
         wait: true
         exact_count: 0
         count_tag:
            Name: "{{ INST_TAG }}"
         instance_tags:
            Name: "{{ INST_TAG }}"
      register: ec2

    - name: run cmd
      shell: |
        shipctl put_resource_state "{{ STATE_RES_NAME }}" "INST_{{ item.ami_launch_index }}_PUBLIC_IP" DELETED
        shipctl put_resource_state "{{ STATE_RES_NAME }}" "INST_{{ item.ami_launch_index }}_ID" DELETED
      with_items: "{{ ec2.instances }}"

    - name: Create ECS Cluster {{ ECS_CLUSTER_NAME }}
      ecs_cluster:
        name: "{{ ECS_CLUSTER_NAME }}"
        state: absent

    - name: run cmd
      shell: |
        shipctl put_resource_state "{{ STATE_RES_NAME }}" CLUSTER_ARN DELETED

