- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    VPC_CIDR_BLOCK: "${VPC_CIDR_BLOCK}"
    VPC_NAME: "${VPC_NAME}"
    VPC_INFO_OUT: "${VPC_INFO_OUT}"
  tasks:
    - name: Destroy VPC {{ VPC_NAME }}
      ec2_vpc_net:
        state: absent
        name: "{{ VPC_NAME }}"
        cidr_block: "{{ VPC_CIDR_BLOCK }}"
        tags:
          module: "{{ VPC_NAME }}"
        tenancy: dedicated
      register: vpc

    - name: run cmd
      shell: |
        shipctl post_resource_state "{{ VPC_INFO_OUT }}" versionName DELETED
