- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    AMI_STATE_RES_NAME: "${AMI_STATE_RES_NAME}"
    VPC_ID: "${VPC_ID}"
  tasks:
    - name: Create internet gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        state: absent

    - name: run cmd
      shell: |
        shipctl post_resource_state "{{ AMI_STATE_RES_NAME }}" VPC_IGW_ID DELETED
