- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    STATE_RES_NAME: "${STATE_RES_NAME}"
    VPC_ID: "${VPC_ID}"
    VPC_SUBNET_ID: "${VPC_SUBNET_ID}"
    VPC_IGW_ID: "${VPC_IGW_ID}"
  tasks:
    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{ VPC_ID }}"
        tags:
          Name: Public
        subnets:
          - "{{ VPC_SUBNET_ID }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ VPC_IGW_ID }}"
      register: publicRT

    - name: run cmd
      shell: |
        shipctl post_resource_state "{{ STATE_RES_NAME }}" versionName "build-${BUILD_NUMBER}"
        shipctl put_resource_state "{{ STATE_RES_NAME }}" VPC_RT_ID "{{ publicRT.route_table.id }}"
