- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    VPC_CIDR_BLOCK: "${VPC_CIDR_BLOCK}"
    VPC_NAME: "${VPC_NAME}"
    AMI_STATE_RES_NAME: "${AMI_STATE_RES_NAME}"
  tasks:
    - name: Create VPC {{ VPC_NAME }}
      ec2_vpc_net:
        name: "{{ VPC_NAME }}"
        cidr_block: "{{ VPC_CIDR_BLOCK }}"
        tags:
          module: "{{ VPC_NAME }}"
        tenancy: dedicated
      register: vpc

    - name: run cmd
      shell: |
        shipctl post_resource_state "{{ AMI_STATE_RES_NAME }}" versionName "build-${BUILD_NUMBER}"
        shipctl put_resource_state "{{ AMI_STATE_RES_NAME }}" VPC_ID "{{ vpc.vpc.id }}"
        shipctl put_resource_state "{{ AMI_STATE_RES_NAME }}" VPC_CIDR_BLOCK "{{ VPC_CIDR_BLOCK }}"
        shipctl put_resource_state "{{ AMI_STATE_RES_NAME }}" VPC_NAME "{{ VPC_NAME }}"
