- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    STATE_RES_NAME: "${STATE_RES_NAME}"
    VPC_ID: "${VPC_ID}"
  tasks:
    - name: Create IGW
      ec2_vpc_igw:
        vpc_id: "{{ VPC_ID }}"
      register: igw

    - name: run cmd
      shell: |
        shipctl post_resource_state "{{ STATE_RES_NAME }}" versionName "build-${BUILD_NUMBER}"
        shipctl put_resource_state "{{ STATE_RES_NAME }}" VPC_IGW_ID "{{ igw.gateway_id }}"

