- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    VPC_SUBNET_CIDR_BLOCK: "${VPC_SUBNET_CIDR_BLOCK}"
    VPC_SUBNET_INFO_OUT: "${VPC_SUBNET_INFO_OUT}"
    VPC_ID: "${VPC_ID}"
  tasks:
    - name: Create Subnet VPC {{ VPC_NAME }}
      ec2_vpc_subnet:
        vpc_id: "{{ VPC_ID }}"
        cidr: "{{ VPC_SUBNET_CIDR_BLOCK }}"
        state: absent

    - name: run cmd
      shell: |
        shipctl post_resource_state "{{ VPC_SUBNET_INFO_OUT }}" VPC_SUBNET_ID DELETED
