- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    VPC_CIDR_BLOCK: "${VPC_CIDR_BLOCK}"
    VPC_NAME: "${VPC_NAME}"
    AMI_STATE_RES_NAME: "${AMI_STATE_RES_NAME}"
  tasks:
    - name: Destroy VPC {{ VPC_NAME }}
      ec2_vpc_net:
        state: absent
        name: "{{ VPC_NAME }}"
        cidr_block: "{{ VPC_CIDR_BLOCK }}"
        tags:
          module: "{{ VPC_NAME }}"
        tenancy: dedicated
      register: vpc

    - name: run cmd
      shell: |
        shipctl post_resource_state "{{ AMI_STATE_RES_NAME }}" VPC_ID DELETED
