- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    VPC_SUBNET_CIDR_BLOCK: "${VPC_SUBNET_CIDR_BLOCK}"
    VPC_SUBNET_NAME: "${VPC_SUBNET_NAME}"
    STATE_RES_NAME: "${STATE_RES_NAME}"
    VPC_ID: "${VPC_ID}"
  tasks:
    - name: Create Subnet VPC {{ VPC_NAME }}
      ec2_vpc_subnet:
        vpc_id: "{{ VPC_ID }}"
        cidr: "{{ VPC_SUBNET_CIDR_BLOCK }}"
        resource_tags:
          Name: "{{ VPC_SUBNET_NAME }}"
      register: publicSN

    - name: run cmd
      shell: |
        shipctl post_resource_state "{{ STATE_RES_NAME }}" versionName "build-${BUILD_NUMBER}"
        shipctl put_resource_state "{{ STATE_RES_NAME }}" VPC_SUBNET_ID "{{ publicSN.subnet.id }}"
        shipctl put_resource_state "{{ STATE_RES_NAME }}" VPC_SUBNET_CIDR_BLOCK "{{ VPC_SUBNET_CIDR_BLOCK }}"
        shipctl put_resource_state "{{ STATE_RES_NAME }}" VPC_SUBNET_NAME "{{ VPC_SUBNET_NAME }}"
