- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    AMI_STATE_RES_NAME: "${AMI_STATE_RES_NAME}"
    VPC_ID: "${VPC_ID}"
    VPC_SUBNET_CIDR_BLOCK: "${VPC_SUBNET_CIDR_BLOCK}"
  tasks:
    - name: Create Public SG group
      ec2_group:
        state: absent
        name: publicSG
        description: Public access Security Group
        vpc_id: "{{ VPC_ID }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: "{{ VPC_SUBNET_CIDR_BLOCK }}"
      register: publicSG

    - debug:
        var: publicSG

#    - name: run cmd
#      shell: |
#        shipctl post_resource_state "{{ AMI_STATE_RES_NAME }}" versionName "build-${BUILD_NUMBER}"
#        shipctl put_resource_state "{{ AMI_STATE_RES_NAME }}" VPC_SUBNET_ID "{{ publicSN.subnet.id }}"
#        shipctl put_resource_state "{{ AMI_STATE_RES_NAME }}" VPC_SUBNET_CIDR_BLOCK "{{ VPC_SUBNET_CIDR_BLOCK }}"
#        shipctl put_resource_state "{{ AMI_STATE_RES_NAME }}" VPC_SUBNET_NAME "{{ VPC_SUBNET_NAME }}"
