jobs:

#---------------------------------------------------------------#
#------------------------- INST PROF Setup -----------------------#
#---------------------------------------------------------------#

# SETUP Instance Profile with TERRAFORM
  - name: setup_inst_prof
    type: runSh
    steps:
      - IN: aws_region
      - IN: inst_tf_state
      - IN: aws_creds
        switch: off
      - IN: ans_sec_ops
        switch: off
      - TASK:
        - script: . /build/IN/ans_sec_ops/gitRepo/tf_createInstProf.sh create
      - OUT: inst_tf_state
      - OUT: infra_state
    on_success:
      - script: echo "SUCCESS"
    on_failure:
      - script: echo "FAILURE"
    always:
      - script: . /build/IN/ans_sec_ops/gitRepo/tf_archiveState.sh inst_tf_state

# PROV AMI VPC with Ansible
  - name: prov_ami_vpc
    type: runSh
    steps:
      - IN: aws_region
      - IN: ami_state_res_name
        switch: off
      - IN: aws_creds
        switch: off
      - IN: ans_sec_ops
        switch: off
      - IN: ami_vpc_conf
      - TASK:
        - script: |
            export AWS_ACCESS_KEY_ID=$(shipctl get_integration_resource_field aws_creds aws_access_key_id)
            export AWS_SECRET_ACCESS_KEY=$(shipctl get_integration_resource_field aws_creds aws_secret_access_key)
            cd $(shipctl get_resource_state ans_sec_ops)
            shipctl replace an_vpc_prov.yml
            ansible-playbook -v an_vpc_prov.yml
      - OUT: infra_state

# PROV AMI VPC Subnet with Ansible
  - name: prov_ami_vpc_subnet
    type: runSh
    steps:
      - IN: aws_region
      - IN: ami_state_res_name
        switch: off
      - IN: infra_state
      - IN: prov_ami_vpc
      - IN: ami_vpc_subnet_conf
      - IN: aws_creds
        switch: off
      - IN: ans_sec_ops
        switch: off
      - TASK:
        - script: |
            export AWS_ACCESS_KEY_ID=$(shipctl get_integration_resource_field aws_creds aws_access_key_id)
            export AWS_SECRET_ACCESS_KEY=$(shipctl get_integration_resource_field aws_creds aws_secret_access_key)
            cd $(shipctl get_resource_state ans_sec_ops)
            pushd $(shipctl get_resource_meta infra_state)
            export VPC_ID=$(cat version.json | jq -r '.'version.propertyBag.VPC_ID)
            popd
            shipctl replace an_vpc_subnet_prov.yml
            ansible-playbook -v an_vpc_subnet_prov.yml
      - OUT: infra_state

# PROV AMI VPC IGW with Ansible
  - name: prov_ami_vpc_igw
    type: runSh
    steps:
      - IN: aws_region
      - IN: ami_state_res_name
        switch: off
      - IN: infra_state
      - IN: prov_ami_vpc_subnet
      - IN: aws_creds
        switch: off
      - IN: ans_sec_ops
        switch: off
      - TASK:
        - script: |
            export AWS_ACCESS_KEY_ID=$(shipctl get_integration_resource_field aws_creds aws_access_key_id)
            export AWS_SECRET_ACCESS_KEY=$(shipctl get_integration_resource_field aws_creds aws_secret_access_key)
            cd $(shipctl get_resource_state ans_sec_ops)
            pushd $(shipctl get_resource_meta infra_state)
            export VPC_ID=$(cat version.json | jq -r '.'version.propertyBag.VPC_ID)
            popd
            shipctl replace an_vpc_igw_prov.yml
            ansible-playbook -v an_vpc_igw_prov.yml
      - OUT: infra_state

# PROV AMI VPC Public RT with Ansible
  - name: prov_ami_vpc_rt
    type: runSh
    steps:
      - IN: aws_region
      - IN: ami_state_res_name
        switch: off
      - IN: infra_state
      - IN: prov_ami_vpc_igw
      - IN: aws_creds
        switch: off
      - IN: ans_sec_ops
        switch: off
      - TASK:
        - script: |
            export AWS_ACCESS_KEY_ID=$(shipctl get_integration_resource_field aws_creds aws_access_key_id)
            export AWS_SECRET_ACCESS_KEY=$(shipctl get_integration_resource_field aws_creds aws_secret_access_key)
            cd $(shipctl get_resource_state ans_sec_ops)
            pushd $(shipctl get_resource_meta infra_state)
            export VPC_ID=$(cat version.json | jq -r '.'version.propertyBag.VPC_ID)
            export VPC_SUBNET_ID=$(cat version.json | jq -r '.'version.propertyBag.VPC_SUBNET_ID)
            export VPC_IGW_ID=$(cat version.json | jq -r '.'version.propertyBag.VPC_IGW_ID)
            popd
            shipctl replace an_vpc_rt_prov.yml
            ansible-playbook -v an_vpc_rt_prov.yml
      - OUT: infra_state

# PROV AMI VPC Public RT with Ansible
  - name: prov_ami_vpc_sg_group
    type: runSh
    steps:
      - IN: aws_region
      - IN: ami_state_res_name
        switch: off
      - IN: infra_state
      - IN: prov_ami_vpc_igw
      - IN: aws_creds
        switch: off
      - IN: ans_sec_ops
        switch: off
      - TASK:
        - script: |
            export AWS_ACCESS_KEY_ID=$(shipctl get_integration_resource_field aws_creds aws_access_key_id)
            export AWS_SECRET_ACCESS_KEY=$(shipctl get_integration_resource_field aws_creds aws_secret_access_key)
            cd $(shipctl get_resource_state ans_sec_ops)
            pushd $(shipctl get_resource_meta infra_state)
            export VPC_ID=$(cat version.json | jq -r '.'version.propertyBag.VPC_ID)
            export VPC_SUBNET_CIDR_BLOCK=$(cat version.json | jq -r '.'version.propertyBag.VPC_SUBNET_CIDR_BLOCK)
            popd
            shipctl replace an_vpc_sg_group_prov.yml
            ansible-playbook -v an_vpc_sg_group_prov.yml
      - OUT: infra_state

# DEPROV AMI with Ansible
  - name: deprov_ami_vpc
    type: runSh
    steps:
      - IN: aws_region
      - IN: ami_state_res_name
        switch: off
      - IN: infra_state
      - IN: ami_vpc_subnet_conf
        switch: off
      - IN: ami_vpc_conf
        switch: off
      - IN: aws_creds
        switch: off
      - IN: ans_sec_ops
        switch: off
      - TASK:
        - script: |
            export AWS_ACCESS_KEY_ID=$(shipctl get_integration_resource_field aws_creds aws_access_key_id)
            export AWS_SECRET_ACCESS_KEY=$(shipctl get_integration_resource_field aws_creds aws_secret_access_key)
            cd $(shipctl get_resource_state ans_sec_ops)
            pushd $(shipctl get_resource_meta infra_state)
            export VPC_ID=$(cat version.json | jq -r '.'version.propertyBag.VPC_ID)
            export VPC_SUBNET_ID=$(cat version.json | jq -r '.'version.propertyBag.VPC_SUBNET_ID)
            export VPC_IGW_ID=$(cat version.json | jq -r '.'version.propertyBag.VPC_IGW_ID)
            popd
            shipctl replace an_ami_deprov.yml
            ansible-playbook -v an_ami_deprov.yml
      - OUT: infra_state


# CREATE AWS AMI used to deploy ECS VMs with PACKER
  - name: build_ecs_ami
    type: runSh
    steps:
      - IN: prov_ami_vpc_sg_group
      - IN: prov_ami_vpc_subnet
      - IN: aws_region
      - IN: ami_create_conf
      - IN: infra_state
      - IN: aws_creds
        switch: off
      - IN: ans_sec_ops
        switch: off
      - TASK:
        - script: . IN/ans_sec_ops/gitRepo/pk_basePack.sh
      - OUT: ami_sec_approved

#---------------------------------------------------------------#
#------------------- BUILD/CI with SHIPPABLE CI ----------------#
#---------------------------------------------------------------#

### PACKAGE sample Node.js into docker container
#  - name: ci-push-docker-hub_runCI
#    type: runCI
#    steps:
#      - OUT: demo_doc_img
#
## DEFINE app micro service
#  - name: create_app_man
#    type: manifest
#    steps:
#      - IN: demo_doc_img
#      - IN: doc_img_opts
#
##---------------------------------------------------------------#
##-------------------- App Release Automation -------------------#
##---------------------------------------------------------------#
#
## PROVISION TEST VMs and ECS cluster with TERRAFORM
#  - name: prov_ecs_test
#    type: runSh
#    steps:
#      - IN: test_tf_state
#      - IN: create_app_man
#      - IN: ami_sec_approved
#        switch: off
#      - IN: test_vpc_conf
#        switch: off
#      - IN: aws_pem
#        switch: off
#      - IN: aws_creds
#        switch: off
#      - IN: auto_repo
#        switch: off
#      - TASK:
#        - script: . /build/IN/auto_repo/gitRepo/awsTestECS/provTestInfra.sh create
#      - OUT: test_env_ecs
#      - OUT: test_tf_state
#    on_success:
#      - script: echo "SUCCESS"
#    on_failure:
#      - script: echo "FAILURE"
#    always:
#      - script: . /build/IN/auto_repo/gitRepo/archiveState.sh awsTestECS test_tf_state
#
## DEPLOY to TEST environment
#  - name: deploy_app_test
#    type: deploy
#    steps:
#      - IN: create_app_man
#        switch: off
#      - IN: test_env_ecs
#      - TASK: managed
#
## RUN System Integration Testing
#  - name: sit
#    type: runSh
#    steps:
#      - IN: sit_repo
#      - IN: deploy_app_test
#      - IN: sit_params
#      - TASK:
#        - script: IN/sit_repo/gitRepo/test.sh sit_params
#    on_success:
#      - script: touch /build/state/success.txt
#    on_failure:
#      - script: touch /build/state/failure.txt
#
## CREATE a production ready release
#  - name: release_app
#    type: release
#    steps:
#      - IN: seed_app_ver
#      - IN: sit
#      - IN: deploy_app_test
#        switch: off
#      - TASK: managed
#        bump: patch

#---------------------------------------------------------------#
#----------------------- CD to Production ----------------------#
#---------------------------------------------------------------#
#
### PROVISION PROD VMs and ECS cluster
#  - name: prov_ecs_prod
#    type: runSh
#    steps:
#      - IN: prod_tf_state
#      - IN: ami_sec_approved
#        switch: off
#      - IN: prod_vpc_conf
#        switch: off
#      - IN: aws_pem
#        switch: off
#      - IN: aws_creds
#        switch: off
#      - IN: auto_repo
#        switch: off
#      - TASK:
#        - script: . /build/IN/auto_repo/gitRepo/awsProdECS/provProdInfra.sh create
#      - OUT: prod_env_ecs
#      - OUT: prod_tf_state
#    on_success:
#      - script: echo "SUCCESS"
#    on_failure:
#      - script: echo "FAILURE"
#    always:
#      - script: . /build/IN/auto_repo/gitRepo/archiveState.sh awsProdECS prod_tf_state
#
## TRIGGER PROD deployment
#  - name: trig_prod_deploy
#    type: runSh
#    steps:
#      - IN: auto_repo
#        switch: off
#      - IN: release_app
#        switch: off
#      - OUT: prod_app_ver
#      - TASK:
#        - script: IN/auto_repo/gitRepo/setVer.sh release_app prod_app_ver

## DEPLOY app to PROD
#  - name: deploy_app_prod1
#    type: deploy
#    steps:
#      - IN: scale_app_prod
#      - IN: trig_prod_deploy
#      - IN: release_app
#        switch: off
#      - IN: prod_env_ecs
#        switch: off
#      - TASK: managed
##        deployMethod: replace

#---------------------------------------------------------------#
#---------------------- DEPROVISION INFRA ----------------------#
#---------------------------------------------------------------#

## DEPROVISION TEST VMs and ECS cluster
#  - name: de_prov_ecs_test
#    type: runSh
#    steps:
#      - IN: test_tf_state
#      - IN: sit
#        switch: off
#      - IN: test_vpc_conf
#        switch: off
#      - IN: aws_creds
#        switch: off
#      - IN: auto_repo
#        switch: off
#      - IN: ami_sec_approved
#        switch: off
#      - TASK:
#        - script: . /build/IN/auto_repo/gitRepo/awsTestECS/provTestInfra.sh destroy
#      - OUT: test_tf_state
#    on_success:
#      - script: echo "SUCCESS"
#    on_failure:
#      - script: echo "FAILURE"
#    always:
#      - script: . /build/IN/auto_repo/gitRepo/archiveState.sh awsTestECS test_tf_state

## DEPROVISION PROD VMs and ECS cluster
#  - name: de_prov_ecs_prod
#    type: runSh
#    steps:
#      - IN: prov_ecs_prod
#        switch: off
#      - IN: prod_tf_state
#      - IN: prod_vpc_conf
#        switch: off
#      - IN: aws_creds
#        switch: off
#      - IN: auto_repo
#        switch: off
#      - IN: ami_sec_approved
#        switch: off
#      - TASK:
#        - script: . /build/IN/auto_repo/gitRepo/awsProdECS/provProdInfra.sh destroy
#      - OUT: prod_tf_state
#    on_success:
#      - script: echo "SUCCESS"
#    on_failure:
#      - script: echo "FAILURE"
#    always:
#      - script: . /build/IN/auto_repo/gitRepo/archiveState.sh awsProdECS prod_tf_state

## DEPROVISION NETWORK
#  - name: de_prov_net
#    type: runSh
#    steps:
#      - IN: setup_net
#        switch: off
#      - IN: net_tf_state
#      - IN: net_conf
#        switch: off
#      - IN: aws_creds
#        switch: off
#      - IN: auto_repo
#        switch: off
#      - TASK:
#        - script: . /build/IN/auto_repo/gitRepo/awsSetupIAM/provNetwork.sh destroy
#      - OUT: net_tf_state
#    on_success:
#      - script: echo "SUCCESS"
#    on_failure:
#      - script: echo "FAILURE"
#    always:
#      - script: . /build/IN/auto_repo/gitRepo/archiveState.sh awsSetupIAM net_tf_state










#---------------------------------------------------------------#
#--------------------------- PROTOTYPE  ------------------------#
#---------------------------------------------------------------#

#########################  TESTING JOB #########################
#  - name: test-job
#    type: runSh
#    steps:
#      - IN: net_conf
#      - IN: aws_creds
#        switch: off
#      - IN: auto_repo
#        switch: off
#      - TASK:
#        - script: . IN/auto_repo/gitRepo/shipUtil.sh
#        - script: . IN/auto_repo/gitRepo/test.sh
#    on_success:
#      - script: echo "SUCCESS"
#    on_failure:
#      - script: echo "FAILURE"
#    always:
#      - script: ls -al

######################### NATIVE WAR CI/CD JOBS #########################
## manifest that defines the Native WAR service definition
#  - name: demo_war_manifest
#    type: manifest
#    steps:
#      - IN: demo_war
#      - IN: demo_war_params
#
## deploy job that deploys native war to cluster of VMs
#  - name: demo_war_test_deploy
#    type: deploy
#    steps:
#      - IN: demo_war_manifest
#        force: true
#      - IN: demo_war_test_cls
#      - TASK:
#        - script: sudo rm -rf /opt/tomcat/webapps/HelloWorld.war
#        - script: sudo cp /tmp/shippable/demo_war_manifest/demo_war/HelloWorld.war /opt/tomcat/webapps/HelloWorld.war
#
